helm:
  parameters:
  - name: image.name
    value: polinchw/hello-github-webhook
    forcestring: true
  - name: image.tag
    value: sha256:17017459e022f40f8eca26b85182df8c3f3bd2ec252f05834a3ac07f2be70643
    forcestring: true
