helm:
  parameters:
  - name: image.name
    value: polinchw/hello-github-webhook
    forcestring: true
  - name: image.tag
    value: sha256:15152728e35d1f415d3e330a5f7fd850c83a31905a83afa4d7f3596d3a9f2d78
    forcestring: true
