helm:
  parameters:
  - name: image.name
    value: polinchw/hello-github-webhook
    forcestring: true
  - name: image.tag
    value: dev-39@sha256:44e9e5232f1fdd1180c6a2c70aaf6f8dec94f758ec04f0e41f0a1b371a911b28
    forcestring: true
