apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-autox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-autox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-autox
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-autox
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.autoxImage }}
        volumeMounts:
        - name: triggers
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: triggers
        configMap:
          name: {{ .Release.Name }}-autox
